urls.py
# app specific urls

from django.conf.urls.defaults import *


urlpatterns = patterns('tamisexport.views',
    url(r'^$', 'tamisexport', name='tamisexport'),
    url(r'^createconnection$', 'tamisexport_create', name='tamisexport_create'),
    url(r'^api/(?P<id>[^/]*)$', 'tamisexport_api', name="tamisexport_api"),
    #url(r'^refreshall$', 'tamisexport_checkrefresh', name="tamisexport_checkrefresh"),
    url(r'^(?P<id>[^/]*)$', 'tamisexport_details', name="tamisexport_details"),
    url(r'^(?P<id>[^/]*)/edit$', 'tamisexport_edit', name="tamisexport_edit"),
    url(r'^(?P<id>[^/]*)/refresh$', 'tamisexport_refresh', name="tamisexport_refresh"),

    url(r'^(?P<id>[^/]*)/delete$', 'tamisexport_delete', name="tamisexport_delete"),
    #url(r'^html$', 'search_page', {'template': 'search/search_content.html'}, name='search_content'),
    #url(r'^api$', 'search_api', name='search_api'),
    #url(r'^api/data$', 'search_api', kwargs={'type':'layer'}, name='layer_search_api'),
    #url(r'^api/maps$', 'search_api', kwargs={'type':'map'}, name='maps_search_api'),
    #url(r'^api/documents$', 'search_api', kwargs={'type':'document'}, name='document_search_api'),
    #url(r'^api/authors$', 'author_list', name='search_api_author_list'),
    #url(r'^form/$', 'advanced_search', name='advanced_search'), 
)

forms.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

import os
import tempfile
import taggit

from django import forms
from django.utils import simplejson as json
from django.utils.translation import ugettext_lazy as _

from tamisexport.models import TAMISConnection



class TAMISConnectionCreateForm(forms.ModelForm):

    tamis_password = forms.CharField(widget=forms.PasswordInput(), required=True)

    class Meta:
        model = TAMISConnection
        exclude = ('creation_date', 'lastedit_date', 'openrefine_projectnumber', 'openrefine_transformation', 'tamis_formname',)

class TAMISConnectionEditForm(forms.ModelForm):

    openrefine_transformation = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = TAMISConnection
        exclude = ('owner', 'creation_date', 'lastedit_date', 'description_con', 'formid', 'title', 'tamis_url','tamis_username','tamis_password','update_freq','openrefine_projectnumber',)

templates/tamisexport/_dataconnection_contentheader.html
{% load url from future %}
{% load i18n %}

<article>
  <div class="content">
    <div class="datatitle">
      TAMIS URL: {{dataconnection.tamis_url}}
    </div>
    <div class="dataabstract">
      TAMIS User Name: {{ dataconnection.tamis_username}}
    </div>
    <div class="dataabstract">
      TAMIS Password: *********
    </div>
  </div> <!-- /.content -->
</article>

templates/tamisexport/_dataconnection_list_item.html
{% load url from future %}
{% load i18n %}

<article>
  <div class="content">
    <h3 class="datatitle">
      {{dataconnection.title}}
    </h3>
    <div class="dataabstract">
      {{ dataconnection.abstract|slice:":255"}}
    </div>
    <div>
      Refreshed: {{ dataconnection.lastedit_date|date:"d b Y H:i a" }}
    </div>
    <div class="dataactions">
      <a href="/tamisexport/{{ dataconnection.id }}" class="button">
        Details
      </a>
      <a href="/tamisexport/{{ dataconnection.id }}/edit" class="button">
        Edit
      </a>
      <a href="/tamisexport/{{ dataconnection.id }}/refresh" class="button button-warn">
        Refresh
      </a>
      <a href="/tamisexport/{{ dataconnection.id }}/delete" class="button button-warn">
        Remove
      </a>
    </div>

  </div> <!-- /.content -->
  <hr size="2px" style="color:black">
</article>

templates/tamisexport/dataconnection_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Confirm Delete" %} - {{ block.super }} {% endblock %}

{% block body_class %}datamanager{% endblock %}

{% block content %}
    <div class="span12">
      <h2 class="page-title">{{dataconnection.title}}</h2>
      <div>
        Are you sure you would like to delete {{dataconnection.title}}?
        <form action="" method="get">
         <input name="confirm" type="submit" value="Confirm" />
         <input name="cancel" type="submit" value="Cancel" />
        </form>
      </div>
    </div>

{% endblock %}

{% block extra_script %}



{% endblock extra_script %}

{% block extra_head %}
{% endblock %}

templates/tamisexport/dataconnection_content.html
{% load i18n %}
<div class="datalist">
{% if object_list|length > 0 %}
{% for dataconnection in object_list %}
    {% include "tamisexport/_dataconnection_list_item.html" %}
{% endfor %}
{% else %}
  <p class="search-count">{% trans "No data found" %}</p>
{% endif %}
</div>

templates/tamisexport/dataconnection_create.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Create Data Connection{% endblock %}

{% block body_class %}datamanager{% endblock %}

{% block content %}

{% if dataconnection %}
    {% include "tamisexport/_dataconnection_contentheader.html" %}
{% endif %}


<form class="form-horizontal" method="POST">


    {% if dataconnection_form.errors %}
	<div style="background-color: pink">{% blocktrans %}Error updating metadata.  Please check the following fields: {% endblocktrans %}
            <ul>
        {% for field in dataconnection_form %}
            {% if field.errors %}
                <li>{{ field.label }}</li>
            {% endif %}
        {% endfor %}


            </ul>
        </div>
    {% endif %}
    <br/>
    {% csrf_token %}
    <div class="form-actions">
      <input type="submit" class="btn btn-primary" value="{% trans "Save" %}"/>
    </div>
    <div class="form-controls">
      {{ dataconnection_form }}
    </div>
    <div class="form-actions">
      <input type="submit" class="btn btn-primary" value="{% trans "Save" %}"/>
    </div>
  </form>

{% endblock %}
{% block extra_script %}
 <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>
{% endblock %}

templates/tamisexport/dataconnection_details.html
{% extends "base.html" %}
{% load i18n %}


{% block title %}Data Connection Details{% endblock %}

{% block body_class %}datamanager{% endblock %}

{% block content %}  


<div class="datacon_content">
  {% include "tamisexport/_dataconnection_list_item.html" %}
  {% include "tamisexport/_dataconnection_contentheader.html" %}
</div>

<div class="extracontent">

    <div>
        Last Time Data was refreshed: {{ dataconnection.lastedit_date|date:"d b Y H:i a" }}
    </div>
    <div>
        Refresh Frequency: {{dataconnection.update_freq}}
    </div>
    <div>
    {{ dataconnection.description }}
    </div>

</div>

{% endblock %}
{% block extra_script %}
 <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
{% endblock %}

templates/tamisexport/dataconnection_edit.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Create Data Connection{% endblock %}

{% block body_class %}datamanager{% endblock %}

{% block content %}

{% if dataconnection %}
    {% include "tamisexport/_dataconnection_contentheader.html" %}
{% endif %}


<form class="form-horizontal" method="POST" class="ORform">


    {% if dataconnection_form.errors %}
	<div style="background-color: pink">{% blocktrans %}Error updating metadata.  Please check the following fields: {% endblocktrans %}
        </div>
    {% endif %}
      <div id="ajaxerror"></div>
        <ul>
          <li>1.Go to OpenRefine URL: <a href="http://localhost:3333/project?project={{dataconnection.openrefine_projectnumber}}" target=="_blank"> http://localhost:3333/project?project={{dataconnection.openrefine_projectnumber}}</a></li>
          <li>2. Make edits</li>
          <li>3. <div id="getORinfo" style="color:red;">Click this</div> to load your operations in the text field</li>
          <li>4. Click save</li> 
        </ul>
            <ul>
        {% for field in dataconnection_form %}
            {% if field.errors %}
                <li>{{ field.label }}</li>
            {% endif %}
        {% endfor %}


            </ul>
    <br/>
    {% csrf_token %}
    <div class="form-actions">
      <input type="submit" class="btn btn-primary" value="{% trans "Save" %}"/>
    </div>
    <div class="form-controls">
      {{ dataconnection_form }}
    </div>
    <div class="form-actions">
      <input type="submit" class="btn btn-primary" value="{% trans "Save" %}"/>
    </div>
  </form>
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>
  $(function() {
    $("#getORinfo").click(function(){
      $(this).html("Working...");
      var projectnumber = {{dataconnection.openrefine_projectnumber}};
      $.getJSON("/tamisexport/api/{{dataconnection.id}}", {"action":"getops"},
          function(data){
            if (data['response'] == "success"){
              $("#id_openrefine_transformation").val(data['operations']);
            }
          });

      $(this).html("Click this");
    });

    window.onbeforeunload = function(){

            alert("There are unsaved changes on this page.  If you leave this page you will lose this information.");

    };
    $('form.ORform').submit(function(){
        window.onbeforeunload = null;
    });
/*
    $(window).on("beforeunload", function() {
        var yes = confirm("You're about to end your session?  All unsaved edits in OpenRefine will be deleted.");
        if (yes) {
          $.getJSON("/tamisexport/api/{{dataconnection.id}}", {"action":"delete"}, function() {
              return "This is a jQuery version";
          });
        }
      }) 
*/


  });
  </script>

{% endblock %}
{% block extra_script %}
 <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
{% endblock %}

templates/tamisexport/datamanager.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Data Manager" %} - {{ block.super }} {% endblock %}

{% block body_class %}datamanager{% endblock %}

{% block content %}
    <div class="span12">
      <h2 class="page-title">{% trans "Data Connections" %}</h2>
      <h2>
      <a href="/tamisexport/createconnection"/>Create New Connection</a>
      </h2>
    </div>
    <div class="span12">
      <div class="row" id="contain-slider">
        <div class="span4">
          {% include "tamisexport/dataconnection_content.html" %}
        </div>

      </div>
    </div>
{% endblock %}

{% block extra_script %}



{% endblock extra_script %}

{% block extra_head %}
{% endblock %}